AWSTemplateFormatVersion: 2010-09-09

Description: Creation of 3 IAM users with varying access levels


Resources:

  IAMUser1:
    Type: AWS::IAM::User
    Properties:
      UserName: ProjectManager 
      LoginProfile: 
        Password: ^tyn6234#))klY
        PasswordResetRequired: true
      Policies: 
        - PolicyName: FullAdminAccess
          PolicyDocument: 
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action: "*"
                Resource: "*"
      Tags: 
        - Key: Name
          Value: AdminIAM

  
  IAMUser2:
    Type: AWS::IAM::User
    Properties:
      UserName: Developer 
      LoginProfile: 
        Password: uueTkl67nmh2))
        PasswordResetRequired: true
      Policies: 
        - PolicyName: EC2FullAccess
          PolicyDocument: 
            Version: "2012-10-17"
            Statement:
              - Effect: "Allow"
                Action: "ec2:*"
                Resource: "*"

              - Effect: "Allow"
                Action: "elasticloadbalancing:*"
                Resource: "*"
      Tags: 
        - Key: Name
          Value: DeveloperIAM


  IAMUser3:
    Type: AWS::IAM::User
    Properties:
      UserName: Intern 
      LoginProfile: 
        Password: 23hhdftGH#s/0w
        PasswordResetRequired: true
      Policies: 
        - PolicyName: S3ListBucket
          PolicyDocument: 
            Version: "2012-10-17"
            Statement:
              - Effect: "Allow"
                Action: "s3:ListBucket"
                Resource: "arn:aws:s3:::*"
      Tags: 
        - Key: Name
          Value: InternIAM